// 大学受験数学・解法データベース（サンプルデータ）
// 各問題は「解法の型」を中心に構造化されている

export const fields = [
  { id: "all", label: "すべて" },
  { id: "ia", label: "数I・A" },
  { id: "iib", label: "数II・B" },
  { id: "iiic", label: "数III・C" },
];

export const problems = [
  {
    id: "p001",
    field: "iib",
    topic: "三角関数",
    title: "和積公式による最大値",
    source: "一橋大 (改題)",
    level: 3,
    statement: "f(\\theta)=\\sin\\theta+\\sin\\left(\\theta+\\dfrac{2\\pi}{3}\\right)+\\sin\\left(\\theta+\\dfrac{4\\pi}{3}\\right) の最大値を求めよ。",
    pattern: "対称な位相のズレは「合成」より「和積で潰す」を疑う",
    steps: [
      { do: "後ろ2項を和積でまとめる", math: "\\sin\\!\\left(\\theta+\\tfrac{2\\pi}{3}\\right)+\\sin\\!\\left(\\theta+\\tfrac{4\\pi}{3}\\right)=2\\sin(\\theta+\\pi)\\cos\\tfrac{\\pi}{3}" },
      { do: "係数を整理する", math: "=2\\sin(\\theta+\\pi)\\cdot\\tfrac12=-\\sin\\theta" },
      { do: "全体を合算すると恒等的に0", math: "f(\\theta)=\\sin\\theta-\\sin\\theta=0" },
    ],
    answer: "恒等的に $f(\\theta)=0$。最大値は $0$",
    insight: "120°ずつズレた3つの正弦波は常に打ち消し合う。三相交流と同じ構造。",
  },
  {
    id: "p002",
    field: "iiic",
    topic: "積分",
    title: "King Property の置換",
    source: "東京大 (類題)",
    level: 4,
    statement: "I=\\displaystyle\\int_0^{\\pi}\\dfrac{x\\sin x}{1+\\cos^2 x}\\,dx を求めよ。",
    pattern: "区間 [0,a] に x が邪魔して入っているなら x→a−x を試す",
    steps: [
      { do: "x を π−x に置換する", math: "I=\\int_0^{\\pi}\\frac{(\\pi-x)\\sin x}{1+\\cos^2 x}\\,dx" },
      { do: "元の I と足して x を消す", math: "2I=\\pi\\int_0^{\\pi}\\frac{\\sin x}{1+\\cos^2 x}\\,dx" },
      { do: "t=\\cos x で置換積分", math: "=\\pi\\int_{-1}^{1}\\frac{dt}{1+t^2}=\\pi\\cdot\\frac{\\pi}{2}" },
    ],
    answer: "$I=\\dfrac{\\pi^2}{4}$",
    insight: "被積分関数の x を消したいときの定石。対称区間との相性が抜群。",
  },
  {
    id: "p003",
    field: "ia",
    topic: "整数",
    title: "互いに素と背理法",
    source: "京都大",
    level: 3,
    statement: "n を自然数とする。n^2+1 と n^2+n+1 が互いに素であることを示せ。",
    pattern: "2式のGCDは「差をとる」で次数を下げる",
    steps: [
      { do: "差をとって公約数 d の正体を絞る", math: "(n^2+n+1)-(n^2+1)=n \\Rightarrow d\\mid n" },
      { do: "d|n を元の式に戻す", math: "d\\mid n^2+1 \\text{ かつ } d\\mid n^2 \\Rightarrow d\\mid 1" },
      { do: "公約数は1のみ", math: "\\therefore \\gcd=1" },
    ],
    answer: "互いに素であることが示された",
    insight: "ユークリッドの互除法の精神。多項式でも「引き算で次数を落とす」。",
  },
  {
    id: "p004",
    field: "iib",
    topic: "数列",
    title: "階差から一般項",
    source: "名古屋大 (改題)",
    level: 2,
    statement: "a_1=1,\\; a_{n+1}=a_n+2n のとき一般項 a_n を求めよ。",
    pattern: "a_{n+1}−a_n が n の式 → 階差数列の和",
    steps: [
      { do: "階差数列を取り出す", math: "b_n=a_{n+1}-a_n=2n" },
      { do: "n≧2 で階差の和を作る", math: "a_n=a_1+\\sum_{k=1}^{n-1}2k=1+n(n-1)" },
      { do: "n=1 でも成立を確認", math: "a_n=n^2-n+1" },
    ],
    answer: "$a_n=n^2-n+1$",
    insight: "階差を使ったら必ず初項で検算する。これを忘れると減点される。",
  },
  {
    id: "p005",
    field: "iiic",
    topic: "極限",
    title: "はさみうちの設計",
    source: "東京工業大",
    level: 4,
    statement: "\\displaystyle\\lim_{n\\to\\infty}\\sqrt[n]{1^n+2^n+\\cdots+n^n} を求めよ。",
    pattern: "n乗の和の n乗根 → 最大項で上下からはさむ",
    steps: [
      { do: "最大項 n^n で下からおさえる", math: "\\sqrt[n]{n^n}=n \\le \\sqrt[n]{\\textstyle\\sum k^n}" },
      { do: "全項を n^n で上からおさえる", math: "\\sqrt[n]{\\textstyle\\sum k^n}\\le \\sqrt[n]{n\\cdot n^n}=n\\sqrt[n]{n}" },
      { do: "両端の極限を一致させる", math: "n\\sqrt[n]{n}\\to n\\cdot1,\\;\\text{比は}\\to1" },
    ],
    answer: "発散（$\\sim n$）。比 $\\sqrt[n]{\\sum k^n}/n \\to 1$",
    insight: "和の中で支配的な項を見抜くのが核心。最大項が全体を決める。",
  },
  {
    id: "p006",
    field: "ia",
    topic: "確率",
    title: "余事象で数える",
    source: "早稲田大",
    level: 2,
    statement: "サイコロを4回投げて、少なくとも1回6が出る確率を求めよ。",
    pattern: "「少なくとも1回」は余事象（1回も出ない）を引く",
    steps: [
      { do: "6が1回も出ない確率", math: "\\left(\\tfrac56\\right)^4=\\tfrac{625}{1296}" },
      { do: "全体から引く", math: "1-\\tfrac{625}{1296}=\\tfrac{671}{1296}" },
    ],
    answer: "$\\dfrac{671}{1296}$",
    insight: "「少なくとも」を見たら反射的に余事象。直接数えると場合分け地獄。",
  },
  {
    id: "p007",
    field: "iib",
    topic: "微分",
    title: "文字定数の分離",
    source: "大阪大",
    level: 3,
    statement: "方程式 x^3-3x=a が異なる3つの実数解をもつ a の範囲を求めよ。",
    pattern: "解の個数は y=f(x) と y=a の交点数に翻訳",
    steps: [
      { do: "定数 a を分離し関数とみなす", math: "g(x)=x^3-3x,\\quad y=a" },
      { do: "極値を求める", math: "g'(x)=3x^2-3=0\\Rightarrow x=\\pm1" },
      { do: "極大・極小の間に a があればよい", math: "g(-1)=2,\\;g(1)=-2" },
    ],
    answer: "$-2<a<2$",
    insight: "「解の個数」は必ずグラフの交点に言い換える。定数分離が王道。",
  },
  {
    id: "p008",
    field: "iiic",
    topic: "複素数",
    title: "回転の合成",
    source: "慶應義塾大",
    level: 3,
    statement: "複素数平面上で点 z を原点まわりに 60° 回転し、さらに 2 倍に拡大した点を w とする。w を z で表せ。",
    pattern: "回転と拡大は「複素数の掛け算」一発",
    steps: [
      { do: "回転＝単位複素数の掛け算", math: "\\text{60°回転}=\\cos60°+i\\sin60°=\\tfrac12+\\tfrac{\\sqrt3}{2}i" },
      { do: "拡大は実数倍", math: "w=2\\left(\\tfrac12+\\tfrac{\\sqrt3}{2}i\\right)z" },
      { do: "整理", math: "w=(1+\\sqrt3\\,i)\\,z" },
    ],
    answer: "$w=(1+\\sqrt3\\,i)z$",
    insight: "幾何の回転・拡大は複素数の積に完全対応。図を描かず計算で済む。",
  },
];

export const stats = {
  problemCount: problems.length,
  patternCount: new Set(problems.map((p) => p.pattern)).size,
  topicCount: new Set(problems.map((p) => p.topic)).size,
};
